<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    <title>@yield('title', 'Inner Balance')</title>
    <link
        rel="preconnect"
        href="https://fonts.googleapis.com"
    >
    <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin
    >
    <link
        href="https://fonts.googleapis.com/css2?family=Literata:opsz@7..72&family=Livvic:wght@200;400;500&family=Roboto:wght@500&display=swap"
        rel="stylesheet"
    >
    <link
        rel="preconnect"
        href="https://fonts.googleapis.com"
    >
    <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin
    >
    <link
        href="https://fonts.googleapis.com/css2?family=Literata:opsz@7..72&family=Livvic:wght@200;400;500&family=Poppins:wght@300;400;500;600;700&family=Roboto:wght@500&display=swap"
        rel="stylesheet"
    >

    <link
        href="https://fonts.cdnfonts.com/css/satoshi"
        rel="stylesheet"
    >
    <link
        rel="preload"
        as="style"
        href="https://innerbalance.com/build/assets/app-a8d862e8.css"
    />
    <link
        rel="modulepreload"
        href="https://innerbalance.com/build/assets/app-cb15a8b1.js"
    />
    <link
        rel="modulepreload"
        href="https://innerbalance.com/build/assets/axios-82afda87.js"
    />
    <link
        rel="stylesheet"
        href="https://innerbalance.com/build/assets/app-a8d862e8.css"
    />
    <script
        type="module"
        src="https://innerbalance.com/build/assets/app-cb15a8b1.js"
    ></script>
    
    @include('layouts::parts.styles')
    @include('layouts::parts.analytics')
</head>
